export const STORAGE_KEYS = {
  addSelection: "selectedAddCourses",
  dropSelection: "selectedDropCourses",
  successfulAdds: "successfulAddCourses",
  droppedCourseIds: "droppedCourseIds",
  submissionMode: "courseSubmissionMode",
  courseFilter: "courseFilter",
};

export const DAYS = ["一", "二", "三", "四", "五"];

export const BASE_SCHEDULE_COURSES = [
  {
    id: "CS203",
    name: "資料庫系統",
    credits: 3,
    teacher: "陳志明",
    time: "二 3-4",
    room: "E302",
    department: "資訊工程學系",
    grade: "二年級",
    source: "原有課表",
  },
  {
    id: "CS221",
    name: "計算機網路",
    credits: 3,
    teacher: "吳承恩",
    time: "三 1-3",
    room: "D305",
    department: "資訊工程學系",
    grade: "二年級",
    source: "原有課表",
  },
  {
    id: "EN204",
    name: "英文簡報",
    credits: 2,
    teacher: "林怡君",
    time: "四 5-6",
    room: "A105",
    department: "應用外語學系",
    grade: "二年級",
    source: "原有課表",
  },
  {
    id: "PE101",
    name: "體育",
    credits: 1,
    teacher: "張國維",
    time: "五 1-2",
    room: "體育館",
    department: "觀光休閒學系",
    grade: "一年級",
    source: "原有課表",
  },
];

export const COURSE_RESULTS = {
  CS201: {
    id: "CS201",
    name: "進階程式設計",
    credits: 3,
    teacher: "陳志明",
    time: "二 3-4",
    room: "E302",
    department: "資訊工程學系",
    grade: "二年級",
    success: false,
    reason: "與既有課表「資料庫系統」二 3-4 衝堂。",
  },
  CS215: {
    id: "CS215",
    name: "資料結構",
    credits: 3,
    teacher: "王慧玲",
    time: "三 1-3",
    room: "E201",
    department: "資訊工程學系",
    grade: "二年級",
    success: false,
    reason: "與既有課表「計算機網路」三 1-3 衝堂。",
  },
  GE118: {
    id: "GE118",
    name: "簡報與表達",
    credits: 2,
    teacher: "林怡君",
    time: "四 5-6",
    room: "A105",
    department: "應用外語學系",
    grade: "二年級",
    success: false,
    reason: "課程名額已滿，無法完成本次加選。",
  },
  PE102: {
    id: "PE102",
    name: "體育二",
    credits: 1,
    teacher: "張國維",
    time: "五 3-4",
    room: "綜合球場",
    department: "觀光休閒學系",
    grade: "一年級",
    success: true,
    reason: "時段未衝堂，已加入本學期課表。",
  },
  CS310: {
    id: "CS310",
    name: "演算法",
    credits: 3,
    teacher: "黃冠勝",
    time: "一 3-4",
    room: "E405",
    department: "資訊工程學系",
    grade: "三年級",
    success: true,
    reason: "時段未衝堂，已加入本學期課表。",
  },
  AR205: {
    id: "AR205",
    name: "動漫繪畫",
    credits: 2,
    teacher: "黃明昌",
    time: "四 1-2",
    room: "A204",
    department: "應用外語學系",
    grade: "一年級",
    success: true,
    reason: "時段未衝堂，已加入本學期課表。",
  },
};
